# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_email', models.CharField(max_length=200)),
                ('member_pw', models.CharField(max_length=200)),
                ('member_fname', models.CharField(max_length=200)),
                ('member_lname', models.CharField(max_length=200)),
                ('member_address', models.CharField(max_length=200)),
                ('member_tel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
