# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsInto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logsinto_email', models.CharField(max_length=200)),
                ('logsinto_pw', models.CharField(max_length=200)),
            ],
        ),
    ]
