# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_logsinto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=200)),
                ('goods_price', models.IntegerField(max_length=10)),
                ('goods_num', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='LogsInto',
        ),
    ]
