# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160420_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.CharField(max_length=200),
        ),
    ]
