# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=200)),
                ('goods_price', models.CharField(max_length=200)),
                ('goods_num', models.CharField(max_length=200)),
            ],
        ),
    ]
