# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:47
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_delete_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=200)),
                ('goods_price', models.CharField(max_length=200)),
                ('goods_num', models.CharField(max_length=200)),
                ('goods_detail', models.CharField(max_length=200)),
                ('goods_photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/static/img/1'), upload_to='')),
            ],
        ),
    ]
