# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_photo',
            field=models.ImageField(storage='fs', upload_to=''),
        ),
    ]
