# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160424_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_photo',
            field=models.ImageField(upload_to='/static/img/1'),
        ),
    ]
