# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20160425_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.IntegerField(),
        ),
    ]
