# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160425_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basket_name', models.CharField(max_length=200)),
                ('Basket_price', models.IntegerField()),
                ('Basket_num', models.IntegerField()),
            ],
        ),
    ]
