# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='Basket_name',
            new_name='basket_name',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='Basket_num',
            new_name='basket_num',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='Basket_price',
            new_name='basket_price',
        ),
    ]
