# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_time',
            field=models.CharField(max_length=200),
        ),
    ]
