# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20160425_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='shipment_tex',
            new_name='shipment_tax',
        ),
    ]
