# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20160425_0244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
