# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20160425_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_tax', models.CharField(max_length=200)),
                ('shipment_date', models.CharField(max_length=200)),
                ('shipment_time', models.CharField(max_length=200)),
                ('shipment_sum', models.IntegerField()),
            ],
        ),
    ]
