# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='basket_name',
            new_name='basket_goods',
        ),
    ]
